// interactive-setup.ts - Interactive setup for Tienda Nube CLI with strong typing

import inquirer from "inquirer";
import { promises as fs } from "fs";
import { existsSync } from "fs";
import path from "path";
import chalk from "chalk";
import { Client } from "basic-ftp";

/**
 * FTP configuration interface for validation
 */
interface FtpConnectionConfig {
  host: string;
  user: string;
  password: string;
  port: number;
  secure: boolean;
  timeout: number;
}

/**
 * Interactive setup answers interface
 */
interface SetupAnswers {
  FTP_HOST: string;
  FTP_USER: string;
  FTP_PASSWORD: string;
  FTP_PORT: string;
  FTP_BASE_PATH: string;
  FTP_TIMEOUT: string;
  DEBUG: boolean;
}

/**
 * Interactive setup for Tienda Nube CLI
 * Prompts user for FTP credentials and creates .env file
 */
export async function runInteractiveSetup(): Promise<void> {
  console.log(chalk.cyan("\n" + "=".repeat(60)));
  console.log(
    chalk.cyan.bold("  Tienda Nube / Nuvemshop CLI - Interactive Setup"),
  );
  console.log(chalk.cyan("=".repeat(60) + "\n"));

  console.log(
    chalk.gray("This wizard will help you configure your FTP connection."),
  );
  console.log(
    chalk.gray(
      "You can find these credentials in your Tienda Nube / Nuvemshop admin panel.\n",
    ),
  );

  // Check if .env already exists
  const envPath = path.join(process.cwd(), ".env");
  if (existsSync(envPath)) {
    const { overwrite } = await inquirer.prompt<{ overwrite: boolean }>([
      {
        type: "confirm",
        name: "overwrite",
        message: chalk.yellow(
          ".env file already exists. Do you want to overwrite it?",
        ),
        default: false,
      },
    ]);

    if (!overwrite) {
      console.log(
        chalk.yellow(
          "\n⚠️  Setup cancelled. Existing .env file was not modified.",
        ),
      );
      return;
    }
  }

  // Prompt for FTP credentials
  const answers = await inquirer.prompt<SetupAnswers>([
    {
      type: "input",
      name: "FTP_HOST",
      message: "FTP Host:",
      default: "ftp.tiendanube.com",
      validate: (input: string) => {
        if (!input.trim()) return "FTP host is required";
        return true;
      },
    },
    {
      type: "input",
      name: "FTP_USER",
      message: "FTP Username:",
      validate: (input: string) => {
        if (!input.trim()) return "FTP username is required";
        return true;
      },
    },
    {
      type: "password",
      name: "FTP_PASSWORD",
      message: "FTP Password:",
      mask: "*",
      validate: (input: string) => {
        if (!input.trim()) return "FTP password is required";
        return true;
      },
    },
    {
      type: "input",
      name: "FTP_PORT",
      message: "FTP Port:",
      default: "21",
      validate: (input: string) => {
        const port = parseInt(input, 10);
        if (isNaN(port) || port < 1 || port > 65535) {
          return "Please enter a valid port number (1-65535)";
        }
        return true;
      },
    },
    {
      type: "input",
      name: "FTP_BASE_PATH",
      message: "FTP Base Path:",
      default: "/",
      validate: (input: string) => {
        if (!input.trim()) return "FTP base path is required";
        if (!input.startsWith("/")) return "Base path must start with /";
        return true;
      },
    },
    {
      type: "input",
      name: "FTP_TIMEOUT",
      message: "FTP Connection Timeout (ms):",
      default: "30000",
      validate: (input: string) => {
        const timeout = parseInt(input, 10);
        if (isNaN(timeout) || timeout < 1000) {
          return "Please enter a valid timeout (minimum 1000ms)";
        }
        return true;
      },
    },
    {
      type: "confirm",
      name: "DEBUG",
      message: "Enable debug mode (verbose logging)?",
      default: false,
    },
  ]);

  // Validate FTP connection
  console.log(chalk.cyan("\n⏳ Validating FTP connection..."));

  const connectionValid = await validateFtpConnection({
    host: answers.FTP_HOST,
    user: answers.FTP_USER,
    password: answers.FTP_PASSWORD,
    port: parseInt(answers.FTP_PORT, 10),
    secure: true,
    timeout: parseInt(answers.FTP_TIMEOUT, 10),
  });

  if (!connectionValid) {
    const { continueAnyway } = await inquirer.prompt<{
      continueAnyway: boolean;
    }>([
      {
        type: "confirm",
        name: "continueAnyway",
        message: chalk.yellow(
          "FTP connection failed. Do you want to save the configuration anyway?",
        ),
        default: false,
      },
    ]);

    if (!continueAnyway) {
      console.log(
        chalk.yellow(
          "\n⚠️  Setup cancelled. Please check your FTP credentials and try again.",
        ),
      );
      return;
    }
  } else {
    console.log(chalk.green("✅ FTP connection successful!"));
  }

  // Create .env file
  const envContent = `# Tienda Nube / Nuvemshop FTP Configuration
# Generated by tiendanube init

FTP_HOST=${answers.FTP_HOST}
FTP_USER=${answers.FTP_USER}
FTP_PASSWORD=${answers.FTP_PASSWORD}
FTP_PORT=${answers.FTP_PORT}
FTP_SECURE=true
FTP_BASE_PATH=${answers.FTP_BASE_PATH}
FTP_TIMEOUT=${answers.FTP_TIMEOUT}
DEBUG=${answers.DEBUG}
`;

  try {
    await fs.writeFile(envPath, envContent, "utf-8");
    console.log(chalk.green("\n✅ .env file created successfully!"));
  } catch (error) {
    const err = error as Error;
    console.error(chalk.red("\n❌ Failed to create .env file:", err.message));
    throw error;
  }

  // Create theme folder if it doesn't exist
  const themePath = path.join(process.cwd(), "theme");
  if (!existsSync(themePath)) {
    try {
      await fs.mkdir(themePath, { recursive: true });
      console.log(chalk.green("✅ theme/ folder created"));
    } catch (error) {
      const err = error as Error;
      console.log(
        chalk.yellow("⚠️  Could not create theme/ folder:", err.message),
      );
    }
  }

  // Display next steps
  console.log(chalk.cyan("\n" + "=".repeat(60)));
  console.log(chalk.cyan.bold("  Setup Complete! 🎉"));
  console.log(chalk.cyan("=".repeat(60) + "\n"));

  console.log(chalk.white("Next steps:\n"));
  console.log(chalk.gray("1. Download your theme:"));
  console.log(chalk.white("   $ tiendanube download\n"));
  console.log(chalk.gray("2. Start watching for changes:"));
  console.log(chalk.white("   $ tiendanube watch\n"));
  console.log(chalk.gray("3. Validate your config files:"));
  console.log(chalk.white("   $ tiendanube check\n"));
  console.log(chalk.gray("For more information, run:"));
  console.log(chalk.white("   $ tiendanube --help\n"));
}

/**
 * Validate FTP connection with provided credentials
 * @param config - FTP configuration
 * @returns True if connection successful
 */
async function validateFtpConnection(
  config: FtpConnectionConfig,
): Promise<boolean> {
  const client = new Client();
  client.ftp.verbose = false; // Suppress output during validation

  try {
    await client.access({
      host: config.host,
      user: config.user,
      password: config.password,
      port: config.port,
      secure: config.secure,
    });

    // Try to list root directory to ensure connection works
    await client.list();

    client.close();
    return true;
  } catch (error) {
    const err = error as Error;
    console.log(chalk.red("\n❌ FTP connection failed:", err.message));
    client.close();
    return false;
  }
}
